using System;
using System.Collections;
using System.IO;
using Balancy.Dictionaries;
using UnityEngine;
using UnityEngine.Networking;

namespace Balancy
{
    internal class UnityFileManager
    {
#if UNITY_WEBGL && !UNITY_EDITOR
        private static bool _preloadComplete = false;

        [AOT.MonoPInvokeCallback(typeof(LibraryMethods.General.PreloadCompleteCallback))]
        private static void OnPreloadComplete()
        {
            Debug.Log("[Balancy] IndexedDB preload completed");
            _preloadComplete = true;
        }
#endif

        public static void Init()
        {
            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            var codePath = Path.Combine(Application.dataPath, "Balancy/AutoGeneratedCode/");
            var config = BalancyConfiguration.Instance;
            if (config != null && !string.IsNullOrEmpty(config.AutogeneratedCodePath))
            {
                var customPath = config.AutogeneratedCodePath;
                if (customPath.StartsWith("/"))
                    customPath = customPath.Substring(1);
                codePath = Path.Combine(Application.dataPath, customPath);
                if (!codePath.EndsWith("/"))
                    codePath += "/";
            }

            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(Application.persistentDataPath, resourcesPath, codePath);
        }

        private static string GetCodePath()
        {
            var codePath = Path.Combine(Application.dataPath, "Balancy/AutoGeneratedCode/");
            var config = BalancyConfiguration.Instance;
            if (config != null && !string.IsNullOrEmpty(config.AutogeneratedCodePath))
            {
                var customPath = config.AutogeneratedCodePath;
                if (customPath.StartsWith("/"))
                    customPath = customPath.Substring(1);
                codePath = Path.Combine(Application.dataPath, customPath);
                if (!codePath.EndsWith("/"))
                    codePath += "/";
            }
            return codePath;
        }

        public static IEnumerator InitRuntime()
        {
            var codePath = GetCodePath();

#if UNITY_WEBGL && !UNITY_EDITOR
            // WebGL: resources come from StreamingAssets via UnityWebRequest preload
            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(Application.persistentDataPath, resourcesPath, codePath);
            DataObjectsManager.Init(Application.persistentDataPath, resourcesPath);

            // Preload files from IndexedDB on WebGL
            Debug.Log("[Balancy] Preloading files from IndexedDB...");
            _preloadComplete = false;
            Balancy.LibraryMethods.General.balancyPreloadFromIndexedDB(OnPreloadComplete);

            // Wait for IndexedDB preload to complete
            while (!_preloadComplete)
            {
                yield return null;
            }

            // Preload files from StreamingAssets
            Debug.Log("[Balancy] Preloading files from StreamingAssets...");
            yield return PreloadStreamingAssets(resourcesPath);
#elif UNITY_ANDROID && !UNITY_EDITOR
            // Android: native AAssetManager keeps the synchronous C++ file contract while
            // reading packaged files lazily, without copying every text asset through C#/JNI.
            var streamingAssetsSubpath = "Balancy/";
            using (var unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
            using (var activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity"))
            using (var assetManager = activity.Call<AndroidJavaObject>("getAssets"))
            {
                Balancy.LibraryMethods.General.balancyInitUnityFileHelperAndroidWithAssetManager(
                    Application.persistentDataPath, streamingAssetsSubpath, codePath,
                    AndroidJNI.GetJavaVM(), assetManager.GetRawObject());
            }

            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            DataObjectsManager.Init(Application.persistentDataPath, resourcesPath);

            FreezeDiagnostics.Log("ANDROID_NATIVE_ASSET_MANAGER ready=True");
            yield return null;
#elif UNITY_IOS && !UNITY_EDITOR
            // iOS can synchronously read the packaged snapshot from the app bundle.
            // WKWebView reaches the same files through balancy-local://, so no startup copy
            // into persistentDataPath is required.
            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(
                Application.persistentDataPath, resourcesPath, codePath);
            DataObjectsManager.Init(Application.persistentDataPath, resourcesPath);
            yield return null;
#else
            // macOS, Windows, Editor: StreamingAssets are directly accessible on the filesystem
            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(Application.persistentDataPath, resourcesPath, codePath);
            DataObjectsManager.Init(Application.persistentDataPath, resourcesPath);
            yield return null;
#endif
        }

#if UNITY_WEBGL && !UNITY_EDITOR
        private static IEnumerator PreloadStreamingAssets(string resourcesPath)
        {
            var manifestPath = Path.Combine(resourcesPath, "balancy_files_manifest.txt");
            var manifestRequest = UnityWebRequest.Get(manifestPath);
            yield return manifestRequest.SendWebRequest();

            if (manifestRequest.result != UnityWebRequest.Result.Success)
            {
                Debug.LogWarning($"[Balancy] No manifest file found in StreamingAssets, skipping preload: {manifestRequest.error}");
                yield break;
            }

            var lines = manifestRequest.downloadHandler.text.Split('\n');
            int filesPreloaded = 0;

            foreach (var line in lines)
            {
                var relativePath = line.Trim().TrimStart('.', '/');
                if (string.IsNullOrEmpty(relativePath) || relativePath == "balancy_files_manifest.txt")
                    continue;

                var fileUrl = Path.Combine(resourcesPath, relativePath);
                var fileRequest = UnityWebRequest.Get(fileUrl);
                yield return fileRequest.SendWebRequest();

                if (fileRequest.result == UnityWebRequest.Result.Success)
                {
                    var fileData = fileRequest.downloadHandler.data;
                    Balancy.LibraryMethods.General.balancyPreloadFileFromStreamingAssets(relativePath, fileData, fileData.Length);
                    filesPreloaded++;
                }
                else
                {
                    Debug.LogWarning($"[Balancy] Failed to preload {relativePath}: {fileRequest.error}");
                }
            }

            Debug.Log($"[Balancy] Preloaded {filesPreloaded} files from StreamingAssets");
        }
#endif


    }
}
