using System;
using System.IO;
using UnityEngine;
using AOT;
using Object = UnityEngine.Object;

namespace Balancy
{
    internal class UnityFileManager
    {
        public static void Init()
        {
            var resourcesPath = Path.Combine(Application.dataPath, "Balancy/Resources/");
            var codePath = Path.Combine(Application.dataPath, "Balancy/AutoGeneratedCode/");
            var config = BalancyConfiguration.Instance;
            if (config != null && !string.IsNullOrEmpty(config.AutogeneratedCodePath))
            {
                var customPath = config.AutogeneratedCodePath;
                if (customPath.StartsWith("/"))
                    customPath = customPath.Substring(1);
                codePath = Path.Combine(Application.dataPath, customPath);
                if (!codePath.EndsWith("/"))
                    codePath += "/";
            }

            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(Application.persistentDataPath, resourcesPath, codePath, LoadFromResources, IsFileExistsInResources, LoadImageAsBase64FromResources);
        }

        [MonoPInvokeCallback(typeof(LibraryMethods.General.IsFileExistsCallback))]
        private static bool IsFileExistsInResources(string path)
        {
            string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(path);

            Object asset = Resources.Load(fileNameWithoutExtension);
            return asset != null;
        }

        [MonoPInvokeCallback(typeof(LibraryMethods.General.LoadFileCallback))]
        private static string LoadFromResources(string path)
        {
            try
            {
                var textFile = Resources.Load<TextAsset>(path);
                // Debug.LogError($"LoadFromResources > {path} > {textFile}");
                return textFile != null ? textFile.text : string.Empty;
            }
            catch (Exception e)
            {
                Debug.LogError(e);
                return string.Empty;
            }
        }
        
        [MonoPInvokeCallback(typeof(LibraryMethods.General.LoadImageBase64Callback))]
        private static string LoadImageAsBase64FromResources(string path)
        {
            try
            {
                string resourcePath = Path.GetFileNameWithoutExtension(path);
                Texture2D texture = Resources.Load<Texture2D>(resourcePath);
                if (texture != null)
                {
                    // Check if texture is readable
                    if (!texture.isReadable)
                    {
                        Debug.LogError($"Texture {resourcePath} is not readable. Enable 'Read/Write' in import settings.");
                        return string.Empty;
                    }
                    
                    // Convert texture to PNG bytes
                    byte[] imageBytes = texture.EncodeToPNG();
                    
                    if (imageBytes == null || imageBytes.Length == 0)
                    {
                        Debug.LogError($"Failed to encode texture {resourcePath} to PNG. Format: {texture.format}");
                        return string.Empty;
                    }
                    
                    // Get MIME type from original path
                    string mimeType = GetMimeTypeFromPath(path);
            
                    // Convert to base64
                    string base64 = System.Convert.ToBase64String(imageBytes);
            
                    return $"data:{mimeType};base64,{base64}";
                }
                else
                {
                    Debug.Log($"Texture not found, trying as TextAsset: {resourcePath}");
                }
        
                // Fallback: try loading as binary asset
                TextAsset binaryAsset = Resources.Load<TextAsset>(resourcePath);
                if (binaryAsset != null)
                {
                    byte[] bytes = binaryAsset.bytes;
                    if (bytes == null || bytes.Length == 0)
                    {
                        Debug.LogError($"TextAsset {resourcePath} has no bytes");
                        return string.Empty;
                    }
                    
                    string mimeType = GetMimeTypeFromPath(path);
                    string base64 = System.Convert.ToBase64String(bytes);
            
                    return $"data:{mimeType};base64,{base64}";
                }
                else
                {
                    Debug.LogError($"Asset not found in Resources: {resourcePath}");
                }
        
                return string.Empty;
            }
            catch (Exception e)
            {
                Debug.LogError($"Failed to load image from resources: {path}, Error: {e.Message}\nStackTrace: {e.StackTrace}");
                return string.Empty;
            }
        }

        private static string GetMimeTypeFromPath(string path)
        {
            string extension = Path.GetExtension(path).ToLowerInvariant();
    
            return extension switch
            {
                ".png" => "image/png",
                ".jpg" or ".jpeg" => "image/jpeg",
                ".gif" => "image/gif",
                ".bmp" => "image/bmp",
                ".webp" => "image/webp",
                ".svg" => "image/svg+xml",
                _ => "application/octet-stream"
            };
        }
    }
}