using System;
using System.Collections;
using System.IO;
using UnityEngine;
using UnityEngine.Networking;

namespace Balancy
{
    internal class UnityFileManager
    {
#if UNITY_WEBGL && !UNITY_EDITOR
        private static bool _preloadComplete = false;
        
        [AOT.MonoPInvokeCallback(typeof(LibraryMethods.General.PreloadCompleteCallback))]
        private static void OnPreloadComplete()
        {
            Debug.Log("[Balancy] IndexedDB preload completed");
            _preloadComplete = true;
        }
#endif

        public static void Init()
        {
            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            var codePath = Path.Combine(Application.dataPath, "Balancy/AutoGeneratedCode/");
            var config = BalancyConfiguration.Instance;
            if (config != null && !string.IsNullOrEmpty(config.AutogeneratedCodePath))
            {
                var customPath = config.AutogeneratedCodePath;
                if (customPath.StartsWith("/"))
                    customPath = customPath.Substring(1);
                codePath = Path.Combine(Application.dataPath, customPath);
                if (!codePath.EndsWith("/"))
                    codePath += "/";
            }

            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(Application.persistentDataPath, resourcesPath, codePath);
        }

        public static IEnumerator InitRuntime()
        {
            var resourcesPath = Path.Combine(Application.streamingAssetsPath, "Balancy/");
            
            // Copy StreamingAssets to PersistentDataPath for platforms that need it
            // This ensures WebView can access all resources from a single directory tree
            if (Application.platform == RuntimePlatform.Android || 
                Application.platform == RuntimePlatform.IPhonePlayer ||
                Application.platform == RuntimePlatform.OSXPlayer ||
                Application.platform == RuntimePlatform.OSXEditor)
            {
                var targetPath = Path.Combine(Application.persistentDataPath, "Balancy/Resources/");
                yield return CopyStreamingAssetsToPath(resourcesPath, targetPath);
                resourcesPath = targetPath;
            }
            
            var codePath = Path.Combine(Application.dataPath, "Balancy/AutoGeneratedCode/");
            var config = BalancyConfiguration.Instance;
            if (config != null && !string.IsNullOrEmpty(config.AutogeneratedCodePath))
            {
                var customPath = config.AutogeneratedCodePath;
                if (customPath.StartsWith("/"))
                    customPath = customPath.Substring(1);
                codePath = Path.Combine(Application.dataPath, customPath);
                if (!codePath.EndsWith("/"))
                    codePath += "/";
            }

            Balancy.LibraryMethods.General.balancyInitUnityFileHelper(Application.persistentDataPath, resourcesPath, codePath);
            
#if UNITY_WEBGL && !UNITY_EDITOR
            // Preload files from IndexedDB on WebGL
            Debug.Log("[Balancy] Preloading files from IndexedDB...");
            _preloadComplete = false;
            Balancy.LibraryMethods.General.balancyPreloadFromIndexedDB(OnPreloadComplete);
            
            // Wait for IndexedDB preload to complete
            while (!_preloadComplete)
            {
                yield return null;
            }
            
            // Preload files from StreamingAssets
            Debug.Log("[Balancy] Preloading files from StreamingAssets...");
            yield return PreloadStreamingAssets(resourcesPath);
#endif
        }

#if UNITY_WEBGL && !UNITY_EDITOR
        private static IEnumerator PreloadStreamingAssets(string resourcesPath)
        {
            var manifestPath = Path.Combine(resourcesPath, "balancy_files_manifest.txt");
            var manifestRequest = UnityWebRequest.Get(manifestPath);
            yield return manifestRequest.SendWebRequest();
            
            if (manifestRequest.result != UnityWebRequest.Result.Success)
            {
                Debug.LogWarning($"[Balancy] No manifest file found in StreamingAssets, skipping preload: {manifestRequest.error}");
                yield break;
            }

            var lines = manifestRequest.downloadHandler.text.Split('\n');
            int filesPreloaded = 0;
            
            foreach (var line in lines)
            {
                var relativePath = line.Trim().TrimStart('.', '/');
                if (string.IsNullOrEmpty(relativePath) || relativePath == "balancy_files_manifest.txt")
                    continue;

                var fileUrl = Path.Combine(resourcesPath, relativePath);
                var fileRequest = UnityWebRequest.Get(fileUrl);
                yield return fileRequest.SendWebRequest();
                
                if (fileRequest.result == UnityWebRequest.Result.Success)
                {
                    var fileData = fileRequest.downloadHandler.data;
                    Balancy.LibraryMethods.General.balancyPreloadFileFromStreamingAssets(relativePath, fileData, fileData.Length);
                    filesPreloaded++;
                }
                else
                {
                    Debug.LogWarning($"[Balancy] Failed to preload {relativePath}: {fileRequest.error}");
                }
            }
            
            Debug.Log($"[Balancy] Preloaded {filesPreloaded} files from StreamingAssets");
        }
#endif
        
        private static IEnumerator CopyStreamingAssetsToPath(string sourcePath, string targetPath)
        {
            if (Directory.Exists(targetPath))
                Directory.Delete(targetPath, true);
            
            Directory.CreateDirectory(targetPath);

            var streamingAssetsBalancyPath = Path.Combine(Application.streamingAssetsPath, "Balancy");
            yield return CopyDirectory(streamingAssetsBalancyPath, targetPath);
        }

        private static IEnumerator CopyDirectory(string sourceDir, string targetDir)
        {
            var manifestPath = Path.Combine(sourceDir, "balancy_files_manifest.txt");
            
            // For platforms where we can access files directly (iOS, macOS, Editor), use File.ReadAllText
            // For Android, we need UnityWebRequest
            string manifestContent;
            
            #if UNITY_ANDROID && !UNITY_EDITOR
            var manifestRequest = UnityWebRequest.Get(manifestPath);
            yield return manifestRequest.SendWebRequest();
            
            if (manifestRequest.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError($"Failed to load manifest: {manifestRequest.error}");
                yield break;
            }
            manifestContent = manifestRequest.downloadHandler.text;
            #else
            // Direct file access for iOS, macOS, Editor
            if (!File.Exists(manifestPath))
            {
                Debug.LogWarning($"Manifest file not found: {manifestPath}");
                yield break;
            }
            manifestContent = File.ReadAllText(manifestPath);
            yield return null; // Yield to maintain coroutine behavior
            #endif

            var lines = manifestContent.Split('\n');
            
            foreach (var line in lines)
            {
                var relativePath = line.Trim().TrimStart('.', '/');
                if (string.IsNullOrEmpty(relativePath) || relativePath == "balancy_files_manifest.txt")
                    continue;

                var sourcePath = Path.Combine(sourceDir, relativePath);
                var targetPath = Path.Combine(targetDir, relativePath);
                var targetDirPath = Path.GetDirectoryName(targetPath);
                
                if (!Directory.Exists(targetDirPath))
                    Directory.CreateDirectory(targetDirPath);

                #if UNITY_ANDROID && !UNITY_EDITOR
                var fileRequest = UnityWebRequest.Get(sourcePath);
                yield return fileRequest.SendWebRequest();
                
                if (fileRequest.result == UnityWebRequest.Result.Success)
                {
                    File.WriteAllBytes(targetPath, fileRequest.downloadHandler.data);
                }
                else
                {
                    Debug.LogError($"Failed to copy {relativePath}: {fileRequest.error}");
                }
                #else
                // Direct file copy for iOS, macOS, Editor
                if (File.Exists(sourcePath))
                {
                    File.Copy(sourcePath, targetPath, true);
                    
                    // Yield periodically to avoid blocking
                    if (lines.Length > 50 && Array.IndexOf(lines, line) % 10 == 0)
                        yield return null;
                }
                #endif
            }
        }
    }
}