plugins {
    id 'com.android.library' version '8.2.0' apply false
}

apply plugin: 'com.android.library'

android {
    namespace 'com.balancy.webview'
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    if (project.hasProperty('unityClassesJar')) {
        compileOnly files(unityClassesJar)
    }
}